#!/usr/bin/env node

/**
 * Script para exportar os outputs do CloudFormation para .env.local do frontend
 * Uso: npm run export-outputs
 */

const { CloudFormationClient, DescribeStacksCommand } = require('@aws-sdk/client-cloudformation');
const fs = require('fs');
const path = require('path');

const STACK_NAME = 'CostGuardianStack';
const REGION = 'us-east-1';
const ENV_FILE_PATH = path.join(__dirname, '../../frontend/.env.local');

async function exportOutputs() {
  console.log('🔍 Buscando outputs do stack CloudFormation...\n');

  const client = new CloudFormationClient({ region: REGION });

  try {
    const command = new DescribeStacksCommand({ StackName: STACK_NAME });
    const response = await client.send(command);

    if (!response.Stacks || response.Stacks.length === 0) {
      console.error(`❌ Stack '${STACK_NAME}' não encontrado na região ${REGION}`);
      process.exit(1);
    }

    const stack = response.Stacks[0];
    const outputs = stack.Outputs || [];

    if (outputs.length === 0) {
      console.error(`❌ Stack '${STACK_NAME}' não possui outputs`);
      process.exit(1);
    }

    console.log(`✅ Stack encontrado: ${stack.StackName}`);
    console.log(`📊 Status: ${stack.StackStatus}\n`);

    // Mapear outputs para variáveis de ambiente
    const outputMap = {
      'APIUrl': 'NEXT_PUBLIC_API_URL',
      'UserPoolId': 'NEXT_PUBLIC_COGNITO_USER_POOL_ID',
      'UserPoolClientId': 'NEXT_PUBLIC_COGNITO_USER_POOL_CLIENT_ID',
      'IdentityPoolId': 'NEXT_PUBLIC_COGNITO_IDENTITY_POOL_ID',
      'CfnTemplateUrl': 'NEXT_PUBLIC_CFN_TEMPLATE_URL',
    };

    const envVars = {};

    outputs.forEach(output => {
      const envKey = outputMap[output.OutputKey];
      if (envKey) {
        envVars[envKey] = output.OutputValue;
        console.log(`✓ ${output.OutputKey} → ${envKey}`);
      }
    });

    // Adicionar região
    envVars['NEXT_PUBLIC_AWS_REGION'] = REGION;
    envVars['NEXT_PUBLIC_AMPLIFY_REGION'] = REGION;
    console.log(`✓ Region → NEXT_PUBLIC_AWS_REGION`);

    // Criar conteúdo do .env.local
    const envContent = Object.entries(envVars)
      .map(([key, value]) => `${key}=${value}`)
      .join('\n');

    const fullContent = `# Auto-generated by export-outputs.js
# Do not edit manually - run 'npm run export-outputs' to update

${envContent}

# Stripe (configure manualmente se necessário)
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...
`;

    // Escrever arquivo
    fs.writeFileSync(ENV_FILE_PATH, fullContent);

    console.log(`\n✅ Arquivo criado: ${ENV_FILE_PATH}`);
    console.log('\n📝 Variáveis exportadas:');
    Object.entries(envVars).forEach(([key, value]) => {
      // Truncar valores longos para exibição
      const displayValue = value.length > 50 ? value.substring(0, 50) + '...' : value;
      console.log(`   ${key}=${displayValue}`);
    });

    console.log('\n✅ Pronto! Agora você pode executar o frontend localmente:');
    console.log('   cd frontend');
    console.log('   npm run dev\n');

  } catch (error) {
    if (error.name === 'ResourceNotFoundException') {
      console.error(`\n❌ Stack '${STACK_NAME}' não encontrado.`);
      console.error('   Certifique-se de ter feito o deploy primeiro: npm run cdk deploy\n');
    } else {
      console.error('\n❌ Erro ao buscar outputs:', error.message);
      console.error('\nDetalhes:', error);
    }
    process.exit(1);
  }
}

exportOutputs();
