AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cost Guardian IAM Role for Cross-Account Access'

Parameters:
  ExternalId:
    Type: String
    Description: 'Unique External ID for AssumeRole Security'
    MinLength: '1'
    MaxLength: '1024'
  PlatformAccountId:
    Type: String
    Default: '123456789012'  # Sua Account ID
    Description: 'Platform Account ID'
  CallbackUrl:
    Type: String
    Description: 'URL de callback para notificar a plataforma sobre a criação da role.'
    AllowedPattern: 'https://.+'

Resources:
  CostGuardianRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CostGuardianDelegatedRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { AWS: !Ref PlatformAccountId } # Simplificado para aceitar a conta raiz
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref ExternalId
      Policies:
        - PolicyName: CostGuardianReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                  - ce:GetCostAndUsageWithResources
                  - health:DescribeEvents
                  - health:DescribeAffectedEntities
                  - cloudwatch:GetMetricData
                  - support:CreateCase
                  - support:DescribeServices
                Resource: '*'

  # Custom Resource para Callback (ativa onboarding)
  CallbackFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          const https = require('https');
          const url = require('url');

          exports.handler = async (event, context) => {
            const responseData = { RoleArn: event.ResourceProperties.RoleArn };
            try {
              if (event.RequestType === 'Create' || event.RequestType === 'Update') {
                const callbackUrl = event.ResourceProperties.CallbackUrl;
                const externalId = event.ResourceProperties.ExternalId;
                const roleArn = event.ResourceProperties.RoleArn;
                const awsAccountId = context.invokedFunctionArn.split(':')[4];

                const postData = JSON.stringify({
                  roleArn: roleArn,
                  awsAccountId: awsAccountId,
                  externalId: externalId
                });

                const options = url.parse(callbackUrl);
                options.method = 'POST';
                options.headers = {
                  'Content-Type': 'application/json',
                  'Content-Length': Buffer.byteLength(postData)
                };

                await new Promise((resolve, reject) => {
                  const req = https.request(options, (res) => res.on('end', resolve));
                  req.on('error', reject);
                  req.write(postData);
                  req.end();
                });
              }
              await sendResponse(event, context, 'SUCCESS', responseData);
            } catch (err) {
              console.error(err);
              await sendResponse(event, context, 'FAILED', responseData, err.toString());
            }
          };

          function sendResponse(event, context, responseStatus, responseData, reason) {
            return new Promise(() => {
              const responseBody = JSON.stringify({
                Status: responseStatus,
                Reason: reason || 'See the details in CloudWatch Log Stream: ' + context.logStreamName,
                PhysicalResourceId: context.logStreamName,
                StackId: event.StackId,
                RequestId: event.RequestId,
                LogicalResourceId: event.LogicalResourceId,
                Data: responseData,
              });

              const options = url.parse(event.ResponseURL);
              options.method = 'PUT';
              options.headers = {
                'Content-Type': '',
                'Content-Length': Buffer.byteLength(responseBody),
              };

              const req = https.request(options, (res) => {
                context.done();
              });
              req.on('error', (error) => {
                console.error('sendResponse Error:', error);
                context.done();
              });
              req.write(responseBody);
              req.end();
            });
          }
      Runtime: nodejs18.x
      Timeout: 30

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  CustomResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt CallbackFunction.Arn
      RoleArn: !GetAtt CostGuardianRole.Arn
      CallbackUrl: !Ref CallbackUrl
      ExternalId: !Ref ExternalId

  ClientHealthEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Encaminha eventos do AWS Health para o Cost Guardian"
      Name: !Sub "cost-guardian-client-${AWS::AccountId}/ClientHealthEventRule"
      EventBusName: "default" # O barramento de eventos padrão da conta do cliente
      EventPattern:
        source:
          - "aws.health"
        detail-type:
          - "AWS Health Event"
      Targets:
        - Arn: !Sub "arn:aws:events:${AWS::Region}:${PlatformAccountId}:event-bus/default"
          Id: "CostGuardianEventBusTarget"
          RoleArn: !GetAtt EventBusRole.Arn

  # Nova IAM Role para permitir que a regra envie eventos para o Event Bus da plataforma
  EventBusRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PutEventsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !Sub "arn:aws:events:${AWS::Region}:${PlatformAccountId}:event-bus/default"

Outputs:
  RoleArn:
    Value: !GetAtt CostGuardianRole.Arn
    Description: 'ARN da Role para colar no app'
  AwsAccountId:
    Value: !Ref "AWS::AccountId"
    Description: 'ID da conta AWS onde a stack foi criada.'